SELECT TABLE_NAME FROM USER_TABLES;

SELECT 'DROP TABLE ' || TABLE_NAME || ' CASCADE CONSTRAINTS;' FROM USER_TABLES;

DROP TABLE ALARMS CASCADE CONSTRAINTS;
DROP TABLE ATTENDANCES CASCADE CONSTRAINTS;
DROP TABLE DEPLOYMENTS CASCADE CONSTRAINTS;
DROP TABLE ENVS CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE WORKPLACES CASCADE CONSTRAINTS;